name: foodify_food_delivery_system
description: "A new Flutter project."

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  
  # Networking
  dio: ^5.4.1
  connectivity_plus: ^7.0.0
  
  # Storage
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^10.0.0
  
  # Utilities
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  
  # UI
  cupertino_icons: ^1.0.8

  image_picker: ^1.0.7
  http: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0-dev.11

   # Testing
  mockito: ^5.4.4
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: OpenSans Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans Italic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf